name: vedprakashportfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  timeline_tile: ^2.0.0
  animated_widgets: ^1.1.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Resume.pdf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/vedxcopy.png"
